---
apiVersion: v1
kind: Pod
metadata:   
  name: mysql-instance
  namespace: mysql-instance 
spec: 
  containers: 
  - name: mysql-instance 
    image: raedsebti/mysql-instance:latest 
    env:
    - name: MYSQL_DATABASE
      value: students
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_USER
      value: devops
    - name: MYSQL_PASSWORD
      value: devops 
...
