---
apiVersion: v1
kind: Pod
metadata:   
  name: nodejs-instance
  namespace: nodejs-instance 
spec: 
  containers: 
  - name: nodejs-instance 
    image: raedsebti/nodejs-instance:latest 
    env: 
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: students
    - name: MYSQL_HOST
      value: 10.244.0.6 
...
